// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByEopl7zv502xwbLrxEYl4-drM_V9Lizk',
    appId: '1:92688619875:web:f4b24132d31ea4416d9b56',
    messagingSenderId: '92688619875',
    projectId: 'webrtc-bdf8e',
    authDomain: 'webrtc-bdf8e.firebaseapp.com',
    storageBucket: 'webrtc-bdf8e.appspot.com',
    measurementId: 'G-2MCDDTPZSG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeqAH9VdhG_kFicnVGPvtfQSgM32vT9V8',
    appId: '1:92688619875:android:c4f4ad55c53fbb976d9b56',
    messagingSenderId: '92688619875',
    projectId: 'webrtc-bdf8e',
    storageBucket: 'webrtc-bdf8e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWawR39nkyWwq9sqLQubCNRGNa8fwFDyU',
    appId: '1:92688619875:ios:b06976481ca76ff36d9b56',
    messagingSenderId: '92688619875',
    projectId: 'webrtc-bdf8e',
    storageBucket: 'webrtc-bdf8e.appspot.com',
    iosBundleId: 'com.example.webrtc',
  );
}
